//         Project / File: Yagasoft.Tools.SolutionMaestro.Core / CrmSchema.cs
// File generated by: CRM Code Generator - Ahmed Elsawalhy (Yagasoft.com)

namespace Yagasoft.Tools.SolutionMaestro.Core
{

	#region ImportJob

	public partial class ImportJob
	{
		public const string DisplayName = "Import Job";
		public const string SchemaName = "ImportJob";
		public const string EntityLogicalName = "importjob";


		#region Enums


		#endregion

		#region Fields

		public const string CompletedOn = "completedon";
		public const string CreatedBy = "createdby";
		public const string CreatedOn = "createdon";
		public const string CreatedByDelegate_CreatedOnBehalfBy = "createdonbehalfby";
		public const string Data = "data";
		public const string ImportContext = "importcontext";
		public const string ImportJobId = "importjobid";
		public const string ModifiedBy = "modifiedby";
		public const string ModifiedOn = "modifiedon";
		public const string CreatedByDelegate_ModifiedOnBehalfBy = "modifiedonbehalfby";
		public const string ImportJobName = "name";
		public const string SolutionOperationContext = "operationcontext";
		public const string Organization = "organizationid";
		public const string Progress = "progress";
		public const string Solution = "solutionid";
		public const string SolutionName = "solutionname";
		public const string StartedOn = "startedon";
		public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
		public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";

		#endregion

		#region Relations

		public static class OneToN
		{
		}
			
		public static class NToOne
		{

			public static class Lookups
			{
			}
		}

		public static class NToN
		{

		}

		#endregion
	}
	
	#endregion


	#region Solution

	public partial class Solution
	{
		public const string DisplayName = "Solution";
		public const string SchemaName = "Solution";
		public const string EntityLogicalName = "solution";


		#region Enums

		public enum IsApiManagedSolutionEnum
		{
			Yes = 1,
			No = 0,
		}
	
		public enum IsinternalsolutionEnum
		{
			Yes = 1,
			No = 0,
		}
	
		public enum PackageTypeEnum
		{
			Managed = 1,
			Unmanaged = 0,
		}
	
		public enum IsVisibleOutsidePlatformEnum
		{
			Yes = 1,
			No = 0,
		}
	
		public enum SolutionTypeEnum
		{
			None = 0,
			Snapshot = 1,
			Internal = 2,
		}
	

		#endregion

		#region Fields

		public const string ConfigurationPage = "configurationpageid";
		public const string CreatedBy = "createdby";
		public const string CreatedOn = "createdon";
		public const string CreatedByDelegate = "createdonbehalfby";
		public const string Description = "description";
		public const string DisplayName_FriendlyName = "friendlyname";
		public const string InstalledOn = "installedon";
		public const string IsApiManagedSolution = "isapimanaged";
		public const string PackageType = "ismanaged";
		public const string IsVisibleOutsidePlatform = "isvisible";
		public const string ModifiedBy = "modifiedby";
		public const string ModifiedOn = "modifiedon";
		public const string ModifiedByDelegate = "modifiedonbehalfby";
		public const string Organization = "organizationid";
		public const string ParentSolution = "parentsolutionid";
		public const string PinpointAssetId = "pinpointassetid";
		public const string PinpointPublisherId = "pinpointpublisherid";
		public const string PinpointSolutionDefaultLocale = "pinpointsolutiondefaultlocale";
		public const string PinpointSolutionId = "pinpointsolutionid";
		public const string Publisher = "publisherid";
		public const string SolutionIdentifierId = "solutionid";
		public const string SolutionPackageVersion = "solutionpackageversion";
		public const string SolutionType = "solutiontype";
		public const string Suffix = "templatesuffix";
		public const string Name = "uniquename";
		public const string UpdatedOn = "updatedon";
		public const string UpgradeInfo = "upgradeinfo";
		public const string Version = "version";
		public const string VersionNumber = "versionnumber";

		#endregion

		#region Relations

		public static class OneToN
		{
			public const string SolutionsOfParentSolution = "solution_parent_solution";
		}
			
		public static class NToOne
		{
			public const string SolutionAsParentSolution = "solution_parent_solution";

			public static class Lookups
			{
			public const string SolutionAsParentSolution = "parentsolutionid";
			}
		}

		public static class NToN
		{

		}

		#endregion
	}
	
	#endregion


}

